
#General configuration options.
[General]
	#Mod ids (in order) to prioritize using items for when generating the cucumber-tags.json file.
	modTagPriorities = ["alltheores", "allthemodium", "mekanism", "create", "thermal","tconstruct", "immersiveengineering", "appliedenergistics2", "occultism", "ftbic"]

