#List of names the merchant can have.
merchantNames = ["Swap-O-Matic", "Emerald Muncher", "Weathered Salesperson"]
#The range within animals can be fed by the feeding trough.
#Range: > -2147483648
feedingTroughRange = 8
#The maximum amount of animals (per type) until the feeding trough stops feeding.
#Range: > -2147483648
feedingTroughMaxAnimals = 8
#The range at which the chicken nest picks up laid eggs.
#Range: > -2147483648
chickenNestRange = 8
#The chance to get a bonus crop when using Green Fertilizer.
#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
fertilizerBonusCropChance = 1.0
#The chance to get a bonus growth when using Red Fertilizer.
#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
fertilizerBonusGrowthChance = 1.0
#The chance for Fertilized Farmland to turn back into regular Farmland (per provided bonus).
#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
fertilizerRegressionChance = 0.0
#Set this to true if you're a modpack dev to see Farming for Blockheads registry warnings in chat. Errors will always display.
showRegistryWarnings = false

