
[Energy]
	#Lv Transfer Rate (how much energy is transferred per tick)
	#Range: 1.0 ~ Infinity
	"Lv Transfer Rate" = 32.0
	#Mv Transfer Rate (how much energy is transferred per tick)
	#Range: 1.0 ~ Infinity
	"Mv Transfer Rate" = 128.0
	#Hv Transfer Rate (how much energy is transferred per tick)
	#Range: 1.0 ~ Infinity
	"Hv Transfer Rate" = 512.0
	#Ev Transfer Rate (how much energy is transferred per tick)
	#Range: 1.0 ~ Infinity
	"Ev Transfer Rate" = 2048.0
	#Iv Transfer Rate (how much energy is transferred per tick)
	#Range: 1.0 ~ Infinity
	"Iv Transfer Rate" = 8192.0
	#The amount of Zaps to FE
	#Range: 1.0 ~ Infinity
	"Zap To Fe Conversion Rate" = 4.0
	#The amount of energy a single use battery can contain
	#Range: 1.0 ~ Infinity
	"Single Use Battery Capacity" = 2400.0
	#Energy a Lv Battery can contain
	#Range: 1.0 ~ Infinity
	"Lv Battery Capacity" = 4000.0
	#Energy a Mv Battery can contain
	#Range: 1.0 ~ Infinity
	"Mv Battery Capacity" = 40000.0
	#Energy a Hv Battery can contain
	#Range: 1.0 ~ Infinity
	"Hv Battery Capacity" = 400000.0
	#Energy a Ev Battery can contain
	#Range: 1.0 ~ Infinity
	"Ev Battery Capacity" = 1.0E7
	#Energy a Lv Battery Box can contain
	#Range: 1.0 ~ Infinity
	"Lv Battery Box Capacity" = 40000.0
	#Energy a Mv Battery Box can contain
	#Range: 1.0 ~ Infinity
	"Mv Battery Box Capacity" = 400000.0
	#Energy a Hv Battery Box can contain
	#Range: 1.0 ~ Infinity
	"Hv Battery Box Capacity" = 4000000.0
	#Energy a Ev Battery Box can contain
	#Range: 1.0 ~ Infinity
	"Ev Battery Box Capacity" = 4.0E7
	#Max length of a cable chain
	#The higher the number, the more tick lag will likely present.
	#Range: 1 ~ 100000
	"Max Cable Length" = 300

[Machines]
	#How many items are processed per fuel in the Iron Furnace
	#Range: 1 ~ 1000
	"Items processed per fuel" = 12
	#Amount of energy is stored in the Basic generator
	#Range: 1.0 ~ 100000.0
	"Basic generator capacity" = 4000.0
	#Energy created from the Basic generator
	#Range: 1.0 ~ 100000.0
	"Basic generator output" = 10.0
	#The internal size of the Geothermal generator
	#Range: 1000 ~ 10000
	"Geothermal generator tank size" = 8000
	#Amount of energy stored in the Geothermal Generator
	#Range: 1.0 ~ 100000.0
	"Geothermal generator capacity" = 2400.0
	#Energy created from the Geothermal generator
	#Range: 1.0 ~ 100000.0
	"Geothermal generator output" = 20.0
	#Amount of energy stored in the Wind Mill
	#Range: 1.0 ~ 100000.0
	"Wind mill capacity" = 100.0
	#The min amount of energy the wind mill can output
	#Range: 0.001 ~ 100000.0
	"Wind mill min output" = 0.3
	#The max amount of energy the wind mill can output
	#Range: 0.001 ~ 1000000.0
	"Wind mill max output" = 6.5
	#Minimum height that the windmill is effective from
	#Range: 0 ~ 250
	"Wind mill min y" = 64
	#Maximum height that the windmill is effective from 
	#Range: 0 ~ 320
	"Wind mill max y" = 320
	#How much rain effects the energy production
	#Range: 0.001 ~ 5000.0
	"Wind mill rain modifier" = 1.2
	#How much thunder effects the energy production
	#Range: 0.001 ~ 5000.0
	"Wind mill thunder modifier" = 1.5
	#Energy created from the Lv solar panel
	#Range: 1.0 ~ 100000.0
	"Lv solar panel output" = 1.0
	#Energy created from the Mv solar panel
	#Range: 1.0 ~ 100000.0
	"Mv solar panel output" = 8.0
	#Energy created from the Hv solar panel
	#Range: 1.0 ~ 100000.0
	"Hv solar panel output" = 64.0
	#Energy created from the Ev solar panel
	#Range: 1.0 ~ 100000.0
	"Ev solar panel output" = 512.0
	#Amount of energy stored in the Nuclear Reactor
	#Range: 1.0 ~ 100000.0
	"Nuclear reactor capacity" = 50000.0
	#Base lengths in ticks a machine takes to process a recipe
	#Range: 1.0 ~ 100000.0
	"Machine recipe base ticks" = 200.0
	#Amount of energy stored in the Powered Furnace
	#Range: 1.0 ~ 100000.0
	"Powered furnace capacity" = 1200.0
	#Energy usage per operation of the powered furnace
	#Range: 0.0 ~ 100000.0
	"Powered furnace use" = 3.0
	#Amount of energy stored in the Macerator
	#Range: 1.0 ~ 100000.0
	"Macerator capacity" = 1200.0
	#Energy usage of the Macerator
	#Range: 0.0 ~ 100000.0
	"Macerator use" = 2.0
	#Amount of energy stored in the Centrifuge
	#Range: 1.0 ~ 100000.0
	"Centrifuge capacity" = 1200.0
	#Energy usage of the Centrifuge
	#Range: 0.0 ~ 100000.0
	"Centrifuge use" = 2.0
	#Amount of energy stored in the Compressor
	#Range: 1.0 ~ 100000.0
	"Compressor capacity" = 1200.0
	#Energy usage of the Compressor
	#Range: 0.0 ~ 100000.0
	"Compressor use" = 2.0
	#Amount of energy stored in the Reprocessor
	#Range: 1.0 ~ 100000.0
	"Reprocessor capacity" = 4000.0
	#Energy usage of the Reprocessor
	#Range: 0.0 ~ 100000.0
	"Reprocessor use" = 8.0
	#Amount of energy stored in the Canning Machine
	#Range: 1.0 ~ 100000.0
	"Canning machine capacity" = 1200.0
	#Energy usage of the Canning machine
	#Range: 0.0 ~ 100000.0
	"Canning machine use" = 1.0
	#Amount of energy stored in the Roller
	#Range: 1.0 ~ 100000.0
	"Roller capacity" = 1200.0
	#Energy usage of the Roller
	#Range: 0.0 ~ 100000.0
	"Roller use" = 3.0
	#Amount of energy stored in the Extruder
	#Range: 1.0 ~ 100000.0
	"Extruder capacity" = 1200.0
	#Energy usage of the Extruder
	#Range: 0.0 ~ 100000.0
	"Extruder use" = 3.0
	#Amount of energy stored in the Antimatter Constructor
	#Range: 1.0 ~ 100000.0
	"Antimatter constructor capacity" = 100000.0
	#Construction boost multiplier
	#Range: 1.0 ~ 100000.0
	"Antimatter constructor boost" = 6.0
	#Amount of energy stored in the Advanced Powered Furnace
	#Range: 1.0 ~ 100000.0
	"Advanced powered furnace capacity" = 10000.0
	#Energy usage of the Advanced powered furnace
	#Range: 0.0 ~ 100000.0
	"Advanced powered furnace use" = 16.0
	#Amount of energy stored in the Advanced Macerator
	#Range: 1.0 ~ 100000.0
	"Advanced macerator capacity" = 10000.0
	#Energy usage of the Advanced macerator
	#Range: 0.0 ~ 100000.0
	"Advanced macerator use" = 16.0
	#Amount of energy stored in the Advanced Centrifuge
	#Range: 1.0 ~ 100000.0
	"Advanced centrifuge capacity" = 10000.0
	#Energy usage of the Advanced centrifuge
	#Range: 0.0 ~ 100000.0
	"Advanced centrifuge use" = 16.0
	#Amount of energy stored in the Advanced Compressor
	#Range: 1.0 ~ 100000.0
	"Advanced compressor capacity" = 10000.0
	#Energy usage of the Advanced compressor
	#Range: 0.0 ~ 100000.0
	"Advanced compressor use" = 16.0
	#Amount of energy stored in the Teleporter
	#Range: 1.0 ~ 100000.0
	"Teleporter capacity" = 100000.0
	#Energy usage of the Teleporter min
	#Range: 0.0 ~ 100000.0
	"Teleporter min use" = 100.0
	#Min distance a teleporter can work over
	#Range: 1.0 ~ 100000.0
	"Teleporter min distance" = 16.0
	#Energy usage of the Teleporter max
	#Range: 0.0 ~ 100000.0
	"Teleporter max use" = 10000.0
	#Max distance a teleporter can work over
	#Range: 1.0 ~ 100000.0
	"Teleporter max distance" = 1200.0
	#Amount of energy stored in the Charge Pad
	#Range: 1.0 ~ 100000.0
	"Charge pad capacity" = 100000.0
	#Amount of energy stored in the Powered Crafting Table
	#Range: 1.0 ~ 100000.0
	"Powered crafting table capacity" = 1200.0
	#Energy usage of the Powered crafting table
	#Range: 0.0 ~ 100000.0
	"Powered crafting table use" = 1.0
	#Amount of energy stored in the Quarry
	#Range: 1.0 ~ 100000.0
	"Quarry capacity" = 10000.0
	#Energy usage of the Quarry
	#Range: 0.0 ~ 100000.0
	"Quarry use" = 3.0
	#Duration taken to mine a block using the quarry
	#Range: 0 ~ 100000
	"Quarry mine ticks" = 40
	#Duration taken to move the quarry to a new location
	#Range: 0 ~ 100000
	"Quarry move ticks" = 10
	#Amount of energy stored in the Pump
	#Range: 1.0 ~ 100000.0
	"Pump capacity" = 10000.0
	#Energy usage of the Pump
	#Range: 0.0 ~ 100000.0
	"Pump use" = 3.0
	#Duration taken to mine a fluid using the pump
	#Range: 0 ~ 100000
	"Pump mine ticks" = 40
	#Duration taken to move the pump to a new location
	#Range: 0 ~ 100000
	"Pump move ticks" = 10
	#Amount of energy stored in the Pump Tank
	#Range: 1 ~ 100000
	"Pump tank capacity" = 100000
	#Determines how effective an item can transport energy to something else
	#Range: 0.0 ~ Infinity
	"Item transfer efficiency" = 20.0
	#To reduce lag, we only update a state of a block every X ticks. This controls how many ticks we wait to update the blocks state.
	#Range: 1 ~ 1000
	"State update ticks" = 6
	#Amount of upgrades allowed in each slot of a machine
	#Range: 1 ~ 64
	"Upgrade limit per slot" = 4
	#Speed increase from a single overclocking upgrade
	#Range: 0.0 ~ 100000.0
	"Overclocker speed" = 1.45
	#Energy usage of the Overclocker
	#Range: 0.0 ~ 100000.0
	"Overclocker energy use" = 1.6
	#Energy cost per storage
	#Range: 0.0 ~ 100000.0
	"Storage upgrade" = 10000.0
	#Chance of producing scrap
	#Range: 0.0 ~ 1.0
	"Scrap chance" = 0.125

[Nuclear]
	#How many blocks in a circular radius the nuke will effect
	#Range: 1.0 ~ 1000.0
	"Nuke Radius" = 1.0
	#The starting radius for a nuclear reactor explosion
	#Range: 1.0 ~ 1000.0
	"Base Nuclear blast radius" = 1.0
	#How much to multiple the above base radius of the explosion
	#Range: 0.001 ~ 100.0
	"Nuclear blast radius multiplier" = 0.001
	#The limit of how large an explosion can be
	#Range: 1.0 ~ 10000.0
	"Nuclear blast limit" = 1.0
	#How much fluid a fluid cell can contain
	#Range: 1 ~ 100000
	"Fluid cell capacity" = 1000
	#Add all fluid cells to creative tab
	"Add all fluid cells" = false
	#Spawn a deamon thread to handle the explosion calculation (experimental)
	"Explosion uses deamon thread" = false

[Equipment]
	#Max energy the Carbon armor can contain
	#Range: 0.0 ~ Infinity
	"Carbon armor capacity" = 1000000.0
	#Max energy the Quantum armor can contain
	#Range: 0.0 ~ Infinity
	"Quantum armor capacity" = 1.5E7
	#Max energy that the elytra can contain
	#Range: 0.0 ~ Infinity
	"Mechanical elytra capacity" = 50000.0
	#How much power is recharged passively
	#Range: 0.0 ~ 100000.0
	"Mechanical elytra recharge" = 1.0
	#Armor damage energy
	#Range: 0.0 ~ Infinity
	"Armor damage energy" = 5000.0
	#Armor flight engery
	#Range: 0.0 ~ Infinity
	"Armor flight energy" = 5.0
	#Boost gained from wearing the armor during flight
	#Range: 0.0 ~ 100000.0
	"Armor flight boost" = 50.0
	#Force used to stop flight
	#Range: 0.0 ~ 100000.0
	"Armor flight stop" = 15.0

["Recipe Generation"]
	#Automatically generate dust from ore recipes
	"Create dust from ore recipes" = true
	#Automatically generate dust from material recipes
	"Create dust from material recipes" = true
	#Automatically generate gem from ore recipes
	"Create gem from ore recipes" = true
	#Automatically generate rod recipes
	"Create rod recipes" = true
	#Automatically generate plate recipes
	"Create plate recipes" = true
	#Automatically generate gear recipes
	"Create gear recipes" = true
	#Automatically canned food recipes
	"Create canned food recipes" = true

