
#WorldGen Settings
[worldgen]

	#Ore Gen Settings
	[worldgen.oregen]

		#Ore Settings
		[worldgen.oregen.silverOre]
			#True to generate this ore.
			generateOre = false
			#The tag for the blocks this ore will spawn in.
			fillerBlockTag = "minecraft:stone_ore_replaceables"
			#The size of veins for this ore.
			#Range: 0 ~ 127
			size = 7
			#The count value for the decorator for this ore.
			#Range: 0 ~ 127
			count = 3
			#Range configuration min height.
			#Range: > -2147483648
			bottomOffset = 5
			#Range configuration max height. A negative max height is interpreted as offset from the top of the world (relevant for nether)
			#Range: > -2147483648
			maximum = 30

		#Ore Settings
		[worldgen.oregen.iesniumOre]
			#True to generate this ore.
			generateOre = true
			#The tag for the blocks this ore will spawn in.
			fillerBlockTag = "minecraft:base_stone_nether"
			#The size of veins for this ore.
			#Range: 0 ~ 127
			size = 3
			#The count value for the decorator for this ore.
			#Range: 0 ~ 127
			count = 10
			#Range configuration min height.
			#Range: > -2147483648
			bottomOffset = 10
			#Range configuration max height. A negative max height is interpreted as offset from the top of the world (relevant for nether)
			#Range: > -2147483648
			maximum = 128

		#Ore Settings
		[worldgen.oregen.silverOreDeepslate]
			#True to generate this ore.
			generateOre = false
			#The tag for the blocks this ore will spawn in.
			fillerBlockTag = "minecraft:deepslate_ore_replaceables"
			#The size of veins for this ore.
			#Range: 0 ~ 127
			size = 7
			#The count value for the decorator for this ore.
			#Range: 0 ~ 127
			count = 3
			#Range configuration min height.
			#Range: > -2147483648
			bottomOffset = -64
			#Range configuration max height. A negative max height is interpreted as offset from the top of the world (relevant for nether)
			#Range: > -2147483648
			maximum = 50

	#Underground Grove Settings
	[worldgen.underground_grove]
		#True to generate underground groves. Should not be changed in most scenarios.
		generateUndergroundGroves = true
		#The chance for a grove to spawn in a chunk (generates 1/groveSpawnChance chunks on average).
		#Range: > 0
		groveSpawnChance = 400
		#The min height for a grove to spawn (applied to the center of the grove, not the floor).
		#Range: 0 ~ 512
		groveSpawnMin = 25
		#The max height for a grove to spawn (applied to the center of the grove, not the ceiling).
		#Range: 0 ~ 512
		groveSpawnMax = 60
		#The chance grass will spawn in the underground grove.
		#Range: 0.0 ~ 1.0
		grassChance = 0.6
		#The chance small trees will spawn in the underground grove.
		#Range: 0.0 ~ 1.0
		treeChance = 0.1
		#The chance vines will spawn in the underground grove.
		#Range: 0.0 ~ 1.0
		vineChance = 0.3
		#The chance glowstone will spawn in the ceiling of the underground grove.
		#Range: 0.0 ~ 1.0
		ceilingLightChance = 0.1
		#The biome types the underground grove cannot spawn in.
		biomeTypeBlacklist = ["NETHER", "END"]

