#Vanilla tweaks
[tweaks]
	[tweaks.lantern_tweaks]
	#Allows ceiling lanterns to fall if their support is broken.Additionally if they fall from high enough they will break creating a fire where they land
	#Allowed Values: ON, OFF, NO_FIRE
	fallin_lanterns = "OFF"
