
[general]
	#Whether crops are affected by seasons.
	seasonal_crops = true
	#How crops behave when out of season.
	#0 = Grow slowly
	#1 = Can't grow
	#2 = Break when trying to grow
	#Range: 0 ~ 2
	out_of_season_crop_behavior = 0
	#Maximum underground Y level out of season crops can be grown below.  Set to -1 to disable feature
	#Range: > -1
	underground_fertility_level = 48
	#Whether to include tooltips on crops listing which seasons they're fertile in. Note: This only applies to listed crops.
	crop_tooltips = true

