
[time_settings]
	#The starting sub season for new worlds.
	#0 = Random, 1 - 3 = Early/Mid/Late Spring
	#4 - 6 = Early/Mid/Late Summer
	#7 - 9 = Early/Mid/Late Autumn
	#10 - 12 = Early/Mid/Late Winter
	#Range: 0 ~ 12
	starting_sub_season = 1
	#Seasons will only apply to dimensons listed here
	whitelisted_dimensions = ["minecraft:overworld"]
	#The duration of a sub season in days
	#Range: > 1
	sub_season_duration = 8
	#If the season should progress on a server with no players online
	progress_season_while_offline = true
	#The duration of a Minecraft day in ticks.
	#This only adjusts the internal length of a day used by the season cycle.
	#It is intended to be used in conjunction with another mod which adjusts the actual length of a Minecraft day.
	#Range: > 20
	day_duration = 24000

[weather_settings]
	#Change the frequency of rain/snow/storms based on the season
	change_weather_frequency = true
	#Generate snow and ice during the Winter season
	generate_snow_ice = true

[aesthetic_settings]
	#Change the foliage colour based on the current season
	change_foliage_color = true
	#Change the grass color based on the current season
	change_grass_color = true
	#Change the birch colour based on the current season
	change_birch_color = true

